In [2]:
#pandas is data manupulation library
#pandas series is like column in table
#1D array

In [3]:
import numpy as np
import pandas as pd

In [4]:
#series from list#list mutabAL
#string
country =['India','Pakisthan','USA','Nepal','Srilanka']
pd.Series(country)

0        India
1    Pakisthan
2          USA
3        Nepal
4     Srilanka
dtype: object

In [5]:
#integer
runs= [13,24,56,79,100]
runs_Ser = pd.Series(runs)

In [6]:
#custom index
marks=[56,67,43,78]
subject=['math','english','hgshasha','dghdgshd']
pd.Series(marks,index=subject)

math        56
english     67
hgshasha    43
dghdgshd    78
dtype: int64

In [7]:









#setting a name
marks = pd.Series(marks,index=subject,name='ram ke marks')
marks

math        56
english     67
hgshasha    43
dghdgshd    78
Name: ram ke marks, dtype: int64

In [8]:
marks={
    'math':45,
    "english":67,
    'science':43,
    "hindi":78}
marks_Series=pd.Series(marks,name='ram ke marks')
marks_Series

math       45
english    67
science    43
hindi      78
Name: ram ke marks, dtype: int64

In [9]:
#size
marks_Series.size

4

In [10]:
#dtype
marks_Series.dtype

dtype('int64')

In [11]:
#name
marks_Series.name

'ram ke marks'

In [12]:
#is_unique
marks_Series.is_unique
pd.Series([1,2,3,1,2,3,5]).is_unique


False

In [13]:
#index
marks_Series.index


Index(['math', 'english', 'science', 'hindi'], dtype='object')

In [14]:
#value
marks_Series.values

array([45, 67, 43, 78])

Series using read_csv


In [21]:
#with one col
subs=pd.read_csv('subs.csv',squeeze=True)
subs

<ipython-input-21-ff7df6d47ced>:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  subs=pd.read_csv('subs.csv',squeeze=True)


0       48
1       57
2       40
3       43
4       44
      ... 
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [22]:
#with one col
subs=pd.read_csv('subs.csv',squeeze=False)
subs

<ipython-input-22-25dbaa23fe84>:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  subs=pd.read_csv('subs.csv',squeeze=False)


Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [25]:
#with two col
vk=pd.read_csv('/content/kohli_ipl .csv',index_col='match_no',squeeze=True)
vk

<ipython-input-25-133528f956c0>:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  vk=pd.read_csv('/content/kohli_ipl .csv',index_col='match_no',squeeze=True)


match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [26]:
vk.size

215

In [27]:
vk.index

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            206, 207, 208, 209, 210, 211, 212, 213, 214, 215],
           dtype='int64', name='match_no', length=215)

In [28]:
vk.values

array([  1,  23,  13,  12,   1,   9,  34,   0,  21,   3,  10,  38,   3,
        11,  50,   2,  22,  19,  16,  15,  20,  38,  19,  24,   7,   2,
        16,  17,  24,  38,  34,  42,  13,  58,   3,  14,  37,   9,  23,
        12,  71,  35,  30,  56,  67,  27,  27,  39,  15,  11,  31,  70,
         8,  35,   8,   6,  57,  22,  16,   4,  16,  18,  45,   9,  36,
         9,   3,  73,  42,  24,  51,  35,  58,  65,   1,  11,   1,  32,
        25,  57,  93,  99,  17,  14,  56,  49,   0,  31,  21,   4,   0,
        35,   0,   4,  10,  27,  67,  38,  73,  13,  41,  18,  51,  62,
        35,   1,  34,  48,  32,  82,  19,  44,   1,  12,  12,  75,  79,
        33,  80, 100,  14,  52, 108,  20,   7, 109,  75, 113,  54,   0,
        54,  62,  28,  64,   0,  10,  55,  20,   6,   5,  58,  31,  21,
        57,  92,  30,  18,  68,  32,   8,  39,  70,  48,  12,   4,   6,
        46,   3,  23,  84,  41,  67,   8, 100,   9,  13,  23,  25,  16,
        18,   9,   7,  29,   1,  72,  43,  43,  90,  48,  14,  3

In [29]:
movies=pd.read_csv('/content/bollywood.csv',index_col='movie',squeeze=True)
movies

<ipython-input-29-288d9f7600c8>:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  movies=pd.read_csv('/content/bollywood.csv',index_col='movie',squeeze=True)


movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...       
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [30]:
movies.size

1500

In [31]:
movies.values

array(['Vicky Kaushal', 'Vicky Ahuja', 'Anupam Kher', ..., 'Vivek Oberoi',
       'Ajay Devgn', 'Akshay Kumar'], dtype=object)

In [32]:
movies.index

Index(['Uri: The Surgical Strike', 'Battalion 609',
       'The Accidental Prime Minister (film)', 'Why Cheat India',
       'Evening Shadows', 'Soni (film)', 'Fraud Saiyaan', 'Bombairiya',
       'Manikarnika: The Queen of Jhansi', 'Thackeray (film)',
       ...
       'Raaz (2002 film)', 'Zameen (2003 film)', 'Waisa Bhi Hota Hai Part II',
       'Devdas (2002 Hindi film)', 'Kaante', 'Hum Tumhare Hain Sanam',
       'Aankhen (2002 film)', 'Saathiya (film)', 'Company (film)',
       'Awara Paagal Deewana'],
      dtype='object', name='movie', length=1500)

In [33]:
#head and tail
movies.head()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
Name: lead, dtype: object

In [34]:
movies.tail()

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [35]:
#samples
movies.sample()

movie
Tubelight (2017 Hindi film)    Salman Khan
Name: lead, dtype: object

In [36]:
movies.sample()

movie
Phhir    Rajniesh Duggall
Name: lead, dtype: object

In [37]:
movies.sample()



movie
Monsoon Shootout    Vijay Varma
Name: lead, dtype: object

In [38]:
movies.value_counts()

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Diganth              1
Parveen Kaur         1
Seema Azmi           1
Akanksha Puri        1
Edwin Fernandes      1
Name: lead, Length: 566, dtype: int64

In [39]:
#sort_values ===inplace
vk.sort_values(ascending=False).head(1).values[0]

113

In [40]:
vk.sort_values(ascending=True).head(1).values[0]

0

In [41]:
subs.sort_values( by='Subscribers gained',ascending=False).head(1).values[0]#head(1)means top 1 record

array([396])

In [42]:
movies.sort_index(ascending=False,inplace=True)
movies

movie
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Zokkomon                       Darsheel Safary
Zindagi Tere Naam           Mithun Chakraborty
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi 50-50                      Veena Malik
                                   ...        
2 States (2014 film)              Arjun Kapoor
1971 (2007 film)                Manoj Bajpayee
1920: The Evil Returns             Vicky Ahuja
1920: London                     Sharman Joshi
1920 (film)                   Rajniesh Duggall
Name: lead, Length: 1500, dtype: object

In [43]:
subs.sum()

Subscribers gained    49510
dtype: int64

In [44]:
#mean meadian mode std var
subs.mean()
print(vk.median())
print(movies.mode())
print(subs.std())
print(vk.var())

24.0
0    Akshay Kumar
Name: lead, dtype: object
Subscribers gained    62.675023
dtype: float64
688.0024777222343


In [45]:
#slicing
vk[5:16]

match_no
6      9
7     34
8      0
9     21
10     3
11    10
12    38
13     3
14    11
15    50
16     2
Name: runs, dtype: int64

In [46]:
subs[5:16]

Subscribers gained
5                   46
6                   33
7                   40
8                   44
9                   74
10                  49
11                  56
12                  49
13                  42
14                  39
15                  44

In [47]:
vk[-5:]

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [48]:
movies[::2]

movie
Zor Lagaa Ke...Haiya!         Meghan Jadhav
Zindagi Tere Naam        Mithun Chakraborty
Zindagi 50-50                   Veena Malik
Zinda (film)                    Sanjay Dutt
Zid (2014 film)              Mannara Chopra
                                ...        
3 Storeys                       Aisha Ahmed
3 Deewarein                Naseeruddin Shah
22 Yards                        Barun Sobti
1971 (2007 film)             Manoj Bajpayee
1920: London                  Sharman Joshi
Name: lead, Length: 750, dtype: object

In [49]:
#fancy indexing
vk[[1,2,3,4]]

match_no
1     1
2    23
3    13
4    12
Name: runs, dtype: int64

In [57]:
#indexing with labels-- fancy indexing
movies['Zindagi Tere Naam']

'Mithun Chakraborty'

In [51]:
#adding new index
marks_Series['evs']=100
marks_Series

math        45
english     67
science     43
hindi       78
evs        100
Name: ram ke marks, dtype: int64

In [52]:
#arithematic oprators
100+ marks_Series

math       145
english    167
science    143
hindi      178
evs        200
Name: ram ke marks, dtype: int64

In [ ]:
10-marks_Series

In [ ]:
#relatinal_ opreator
vk>=50

In [ ]:
subs <=30

boolean indexing on series


In [ ]:
#find no of 50's and 100 scored by kohli
vk[vk>=50].size

In [ ]:
#find number of duks
vk[vk==0].size

In [ ]:
#count number of day when

In [ ]:
#when we count greater than 20
num_movies=movies.value_counts()
num_movies[num_movies>20]

In [ ]:
subs.plot()

In [ ]:
vk.plot()

In [ ]:
movies.plot()

In [ ]:
movies.value_counts().head(20).plot(kind='pie')

In [ ]:
#astype
import sys
sys.getsizeof(vk)

In [ ]:
sys.getsizeof(vk.astype('int16'))

In [ ]:
#between
vk[vk.between(51,99)].size

In [ ]:
subs.clip(100,200)

In [ ]:
#drop duplicates
temp=pd.Series([1,2,4,5,6,6,8,8,8])
temp
temp.drop_duplicates(keep='last')

In [ ]:
temp.duplicated().sum()

In [ ]:
#dropna
vk.dropna

In [ ]:
#fillna
vk.fillna(vk.mean())

In [ ]:
fillna

In [ ]:
#apply